const express = require('express');
const path = require('path');
const cors = require('cors');
const sequelize = require('./config/database');
const fileRoutes = require('./routes/fileRoutes');
const adminAuthRoutes = require('./routes/adminAuthRoutes');
const activityRoutes = require('./routes/activityRoutes');
const coreActivityRoutes = require('./routes/coreActivityRoutes');
const ticketCategoryRoutes = require('./routes/ticketCategoryRoutes');
const testimonialRoutes = require('./routes/testimonialRoutes');
const faqCategoryRoutes = require('./routes/faqCategoryRoutes');
const faqRoutes = require('./routes/faqRoutes');
const homeBannerRoutes = require('./routes/homeBannerRoutes');
const rolesRoutes = require('./routes/rolesRoutes');
const subAdminRoutes = require('./routes/subAdminRoutes');
const knowledgeCenterRoutes = require('./routes/knowledgeCenterRoutes');
const locationRoutes = require('./routes/locationRoutes');
const buyerRoutes = require('./routes/buyerRoutes');
const membershipPlanRoutes = require('./routes/membershipPlanRoutes');
const categoriesRoutes = require('./routes/categoriesRoutes');
const subCategoryRoutes = require('./routes/subCategoryRoutes');
const interestCategoriesRoutes = require('./routes/interestCategoriesRoutes');
const interestSubCategoriesRoutes = require('./routes/interestSubCategoriesRoutes');
const subSubCategoriesRoutes = require('./routes/subSubCategoriesRoutes');
const ticketRoutes = require('./routes/ticketRoutes');
const sellerRoutes = require('./routes/sellerRoutes');
const applicationRoutes = require('./routes/applicationRoutes');
const productsRoutes = require('./routes/productsRoutes');
const settingRoutes = require('./routes/settingRoutes');
const newsletterRoutes = require('./routes/newsletterRoutes');
const enquiriesRoutes = require('./routes/enquiriesRoutes');
const openEnquiriesRoutes = require('./routes/openEnquiriesRoutes');
const seoPagesRoutes = require('./routes/seoPagesRoutes');
const userActivityRoutes = require('./routes/userActivityRoutes');
const sellerMailHistoriesRoutes = require('./routes/sellerMailHistoriesRoutes');
const contactsRoutes = require('./routes/contactsRoutes');
const emailsRoutes = require('./routes/emailsRoutes');

const app = express();
app.use(cors());
app.use(express.json());

app.use('/upload', express.static(path.join(__dirname, 'upload')));
app.use('/api/files', fileRoutes);
app.use('/api/admin', adminAuthRoutes);
app.use('/api/activities', activityRoutes);
app.use('/api/core_activities', coreActivityRoutes);
app.use('/api/ticket_categories', ticketCategoryRoutes);
app.use('/api/testimonials', testimonialRoutes);
app.use('/api/faq_categories', faqCategoryRoutes);
app.use('/api/faqs', faqRoutes);
app.use('/api/home_banners', homeBannerRoutes);
app.use('/api/roles', rolesRoutes);
app.use('/api/sub_admin', subAdminRoutes);
app.use('/api/knowledge_center', knowledgeCenterRoutes);
app.use('/api/location', locationRoutes);
app.use('/api/buyers', buyerRoutes);
app.use('/api/membership_plan', membershipPlanRoutes);
app.use('/api/categories', categoriesRoutes);
app.use('/api/sub_categories', subCategoryRoutes);
app.use('/api/interest_categories', interestCategoriesRoutes);
app.use('/api/interest_sub_categories', interestSubCategoriesRoutes);
app.use('/api/sub_sub_categories', subSubCategoriesRoutes);
app.use('/api/tickets', ticketRoutes);
app.use('/api/sellers', sellerRoutes);
app.use('/api/applications', applicationRoutes);
app.use('/api/products', productsRoutes);
app.use('/api/settings', settingRoutes);
app.use('/api/newsletters', newsletterRoutes);
app.use('/api/enquiries', enquiriesRoutes);
app.use('/api/open_enquiries', openEnquiriesRoutes);
app.use('/api/seo_pages', seoPagesRoutes);
app.use('/api/user_activity', userActivityRoutes);
app.use('/api/seller_mail_histories', sellerMailHistoriesRoutes);
app.use('/api/contacts', contactsRoutes);
app.use('/api/emails', emailsRoutes);

sequelize.sync().then(() => {
  console.log('MySQL connected and models synced');
  app.listen(5000, () => console.log('Server running on http://localhost:5000'));
}).catch(err => console.error('DB connection error:', err));
